### ISSUE TITLE
ERROR OPENING TIFF

### ISSUE THREAD

**Issue by hf877839706** [JJPPeters/Strainpp#10]
Dear:
     StraIn++ always show " ERROR OPENNING TIFF". How can I do? Thanks!

**Comment by JJPPeters** [comment]
That error is caused by LibTIFF not being able to open your tiff file.
Specifically the TIFFOpen function: http://www.libtiff.org/man/TIFFOpen.3t.html

Does your tiff open in other software?
Is the tiff open in other software that may block read access to Strain++?

**Comment by hf877839706** [comment]
Thanks for you help. YES, I can open tiff files with GMS and microsoft image manager. But it is error when open with strain++.I change the system still display error.

**Comment by hf877839706** [comment]
My system is windows.

**Comment by hf877839706** [comment]
[220211-33 SLDZ-0006.zip](https://github.com/JJPPeters/Strainpp/files/8920381/220211-33.SLDZ-0006.zip)
This is my file

**Comment by hf877839706** [comment]
Thanks! The reason is PATH of files must be English.

**Comment by JJPPeters** [comment]
Thanks for the update.

As this is an issue with LibTIFF, I unfortunately cannot solve it here.
