### ISSUE TITLE
A bug in export .bin data using strain++ v1.5

### ISSUE THREAD

**Issue by zhangxundi** [JJPPeters/Strainpp#4]
I want export the raw data (.bin) for further analysis using Python. But I found that the distortion data of exx, eyy, exy, eyx export as .bin are totally same: 
![image](https://user-images.githubusercontent.com/39579945/77219228-b5ddad80-6b6e-11ea-8215-e9b4ca32fd58.png)

It will be very helpful if the problem could be fixed, thank you! 

The software I used was: Strain++ v1.5 installer (Win x64)

**Comment by JJPPeters** [comment]
I'm unable to reproduce this on my end. If I save the data as a .bin and open it using ImageJ, I get the correct strain maps.

I also cannot see anyhing within the code that could cause this. I'm assuming the displayed strain within Strain++ looks correct?

Could I ask you to check the output with ImageJ, to make sure this is a problem with the Strain++ output?

Failing that, you could try using the .tif output ("Data image"), it will be a 32-bit floating point image, so should be suitable for loading into python for further analysis.

Thanks.
