### ISSUE TITLE
1.6 crashes with some images?

### ISSUE THREAD

**Issue by thomasaarholt** [JJPPeters/Strainpp#6]
I notice that some dm3 / dm4 files crash Strain++ on file open.

This is a single image saved via GMS 3.4 from a dataset taken with SmartAlign. As far as I know, there is nothing "special" about the data. I'd appreciate if you have any advice.
[Fe ZnO_HAADF_30.zip](https://github.com/JJPPeters/Strainpp/files/5559406/Fe.ZnO_HAADF_30.zip)

**Comment by JJPPeters** [comment]
I have tested this file with the 1.7 release and it now works successfully for me.
