### ISSUE TITLE
Units of Final Image

### ISSUE THREAD

**Issue by mmw0909** [JJPPeters/Strainpp#8]
Hi Dr. Peters, I have tried to use your package to do some analysis, but one question about the final result is what is the unit? I notice both strain and distortion have the same scale with maximum of 0.200, is the unit just arbitrary does it have any physical meaning, for example, percentage for strain and pixels for distortion? Thanks a lot for your time.

**Comment by JJPPeters** [comment]
The units are standard strain values (i.e. ratios), i.e. they are changes in the structure given in fractions of the defined reference dimensions (given by the refined G-vectors).

For example 0.2 is a 20% increase (tensile) over the reference lattice, similarly -0.2 is decrease (compression)
