### ISSUE TITLE
data output

### ISSUE THREAD

**Issue by wsfsz123** [JJPPeters/Strainpp#9]
Dear Professor, can I output the strain data to a new data file?

Thanks!

**Comment by JJPPeters** [comment]
Your question is unclear. Do you want some functionality different to the current File->Export menu?

**Comment by wsfsz123** [comment]
I have solved it. But, I have several questions referring to your program and GPA theory in the papers of M.J. Hytch, Ultramicroscopy, 1998 and J.L. Rouviere, Ultramicroscopy, 2005.

1.  During the calculation of the reduced (refine) phase P_g_{i}(r), which is P’_g_{i}(r) - 2*pi*g*r, where P’_g_{i}(r) is the raw-phase image (Eqs. 2&4 in Rouviere 2005), g_{i} is the manual selected g-vector. Then, what is the g represents, is it g(O) or g_{i}? Where O is the selective refine region (reference) and g(O) is the refined g-vector. And how do you refined g-vector?

2. During the calculation of displacement, P_g(r) = -2 * pi * g * u (Eq. 20 of Hytch 1998), then what is g represent here, g_{i} or g(O)? I am confused about it because it defines the Lagrangian or Euler displacement/strain.

3. Should the refine regions be selected as the same for the two g-vectors?

Thanks!

**Comment by JJPPeters** [comment]
> I have solved it

This helps no one. Please explain how you have solved it so that I can help make sure this doesn't happen, or so future users can see how to solve the problem themselves.

The other questions are not relevant to this issue. I see you have already decided to email me directly so I will address them there.

**Comment by wsfsz123** [comment]
In the output of strain++, it seems only figures are available, I was wondering if I can directly output the strain field in data format, so I can do some postprocessing with the data directly. What I am now doing is using Matlab to read the pixel information of the figure, then transfer it to strain, and it works.

**Comment by JJPPeters** [comment]
There are options to export RGB images and data images (and raw binary). Data images are 32-bit tiff values with the quantitative values, I believe this is what you want.

**Comment by zhangxiangping** [comment]
> There are options to export RGB images and data images (and raw binary). Data images are 32-bit tiff values with the quantitative values, I believe this is what you want.

Dear Professor, how can I get the data from the raw binary file by matlab? I don't understand the data structure for the detail! I hope you can teach me transform it to excel file or txt file!

Thanks!

**Comment by JJPPeters** [comment]
I believe the binary format is raw 64-bit floating point little-endian data.

It is literally just the image data, no information on the image size or otherwise so you will have to note that down yourself.

**Comment by zhangxiangping** [comment]
Thank you very much!

发自我的iPhone
